services:
  
  data-distillery-api:
    hostname: data-distillery-api
    container_name: data-distillery-api
    # Map host machine port 6666 to container port 8080
    # Only root can listen on ports below 1024, we use higher-numbered ports
    # since nginx is running under non-root user hubmap
    ports:
      - "6666:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      # UID and GID 1001 to match the hive user by default
      - HOST_GID=${HOST_GID:-1006}
      - HOST_UID=${HOST_UID:-1006}
    init: true
    restart: always
    volumes:
      # Mount the app config to container in order to keep it outside the image
      - "../src/data_distillery_api/instance:/usr/src/app/src/data_distillery_api/instance"
      # Mount the logging to container
      - "../log:/usr/src/app/log"
      # Mount conf.d on host machine to the nginx conf.d on container
      - "./ubkg-api/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - data_distillary_network
    # Send docker logs to AWS CloudWatch
    # logging: 
    #   driver: awslogs
    #   options:
    #     awslogs-region: us-east-1
    #     awslogs-group: data-distillery-api-docker-logs
    #     awslogs-stream: ${LOG_STREAM}

networks:
  # This is the network created by gateway to enable communicaton between multiple docker-compose projects
  data_distillary_network:
    external: true
